server:
  port: '8081'
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: news_feed_kt
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dunice
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: news_feed
  jpa:
    hibernate:
      ddl-auto: create
    database-platform:
    generate-ddl: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
